### ISSUE TITLE
MessageUpdateHandler is outdated

### ISSUE THREAD

**Issue by KILLEliteMaste** [Javacord/Javacord#1048]
The MessageUpdateHandler is outdated and for example does not update the message if components have been changed and also does not fire an event in this case

**Comment by ShindouMihou** [comment]
Also for interaction original updates, the message edit listener isn't triggered since it doesn't meet the if-check which is `edited_timestamp` since the message is technically not edited at all. (more details on Discord, leaving here for going back to it when needed https://discord.com/channels/151037561152733184/151326093482262528/996490629716639807)

![image](https://user-images.githubusercontent.com/69381903/178581269-0ad123e5-a3f6-495d-8cc0-1dea9b657f7e.png)
