### ISSUE TITLE
API corresponding to Optional`s

### ISSUE THREAD

**Issue by manuelkollus** [Javacord/Javacord#418]
I would like to ask you guys if you could commit an api change corresponding to the 'Optional's. These are dissappointing for many people, especially beginners, and i would love to see a better solution.

**Comment by Saladoc** [comment]
Could you explain what precisely you mean? It is difficult to make out the idea you're conveying here.

**Comment by WalkerKnapp** [comment]
The issue that you got a NoSuchElementException there is the benefit of using Optionals. If they weren't used, you would instead just get a NullPointerException, as the message doesnt exist in the cache. We can't just "provide the message", because we have no message. Optionals as a wrapper make it easier to handle these instances where the data doesn't exist with its utility methods, but returning objects as null leaves multi-line, often "ugly" code.

**Comment by manuelkollus** [comment]
In this case, of course, they are right, but you could still include this in the MessageDeleteEvent, so that you can handle the "older" messages stack free.

**Comment by cap5lut** [comment]
You can not. Not all messages are in the message cache, when the `MessageDeleteEvent` is triggered, the message was already deleted by Discord's side, making it impossible to retrieve the actual message, and thus `MessageDeleteEvent` provides only an `Optional<Message>` as well.

**Comment by BoneyIsSpooky** [comment]
Since this is an issue with your understanding of the API, and not the API per se, this issue should be closed and discussion should be moved to our [discord server](https://discord.gg/0qJ2jjyneLEgG7y3).

**Comment by burdoto** [comment]
@manuelkollus You can always use the `Optional` instance method `#orElse(null)` on any returned `Optional`, if you would rather handle `null`s than `Optional`s. That will either give you the value, if available, and otherwise will return `null`.
This is considered bad style, but it can help if you fail to get your head around the `Optional` Java API.
However, I would still suggest that you try to learn how to use them, as they can come in really handy. You are also always free to ask questions, anywhere. _(don't forget that we all started somewhere)_
