### ISSUE TITLE
getMessagesBeforeAsStream does not stream correctly

### ISSUE THREAD

**Issue by burdoto** [Javacord/Javacord#515]
This method:
```java
    public static Optional<Message> previous(Message before) {
        return before.getChannel()
                .getMessagesBeforeAsStream(before)
                .sorted(Comparator.<Message>comparingLong(DiscordEntity::getId) // simple ID comparison will sort by age
                        .thenComparing(Comparator.reverseOrder())) // then reverse for first message only
                .limit(1) // only once
                .findFirst();
    }
```
will (most often?) return an optional of the _first_ message of a channel, rather than the last one before the given message.
When consuming a whole stream before returning, the result should be expected to be forced to the correct value:
```java
                .getMessagesBeforeAsStream(before)
                .sorted(Comparator.<Message>comparingLong(DiscordEntity::getId) // simple ID comparison will sort by age
                        .thenComparing(Comparator.reverseOrder())) // then reverse for first message only
                .collect(Collectors.toList())
                .stream()
                .findFirst();
```
However, the result is the same.

**Comment by Vampire** [comment]
The stream streams correctly, your comparator is wrong.
`.thenComparing` as the name implies, is only used if two messages have the same ID.
As two message never have the same ID, the `.thenComparing` part is a no-op effectively.
What you want is `comparingLong(DiscordEntity::getId).reversed()`.

And in case this was not just for show-casing the problem you think there is, the sorting is not necessary, as the sorting you apply is the order in which the stream is sorted anyway.

Actually you waste much of time and resources, as by using `.sorted` the whole stream has to be processed, otherwise a sort could not be done, which means all messages of the channel (before `before` have to be requested from the API in batches of 100. Besides needing time, if you do it too often, Discord could complain to you.

Actually also the limit is not necessary here, but it is not a big loss.

So this should be sufficient: `before.getChannel().getMessagesBeforeAsStream(before).findFirst();`

And to make it even better, just use `before.getMessagesBefore(1);` which also has the benefit of not being blocking like the `AsStream` methods, but properly working asynchronous and also only needs to request the message needed instead of a batch of 100 which is how our streaming implementation works. :-)

**Comment by burdoto** [comment]
Ah, good. I though I was missing something dumb, thanks for your fix proposal!
