### ISSUE TITLE
Global Ratelimiter Not Working

### ISSUE THREAD

**Issue by AyuAi** [Javacord/Javacord#577]
I have a section of code that is intended to dish out an absolute ton of bans across multiple servers, and as far as I understood this would be totally OK if I utilized the global ratelimiter on Javacord. Unfortunately, it did not work and I continually hit the global ratelimit when dishing out the bans.

The code that runs the bans:
```
servers.forEach(server -> users
                .stream().reduce(CompletableFuture.completedFuture(null),
                        (cf, user) -> cf.whenComplete((ignored, alsoIgnored) -> server
                                .banUser(user, 7,"Poolban ("+poolId+"): "+shortReason)
                                .exceptionally(ExceptionLogger.get())),
                        (cf1, cf2) -> { throw new AssertionError(); }));
```

When the code runs, it hits the global ratelimit nonstop.

https://i.ayu.dev/img/FzYRU4ZmFCP.png
https://i.ayu.dev/img/hvtGJr2gBxt.png

I believe this may be an error within Javacord, as I should not be hitting the ratelimit this frequently during the code's execution (actually, it shouldn't happen at all if it is working as intended if I understand correctly).

**Comment by Bastian** [comment]
> as I should not be hitting the ratelimit this frequently

What is the frequency? It should be at max 25 requests per seconds.

Unfortunately we cannot ratelimit the global ratelimits as perfectly as we can ratelimit other endpoints because we have no information when one "bucket" starts and when it gets reset (until we actually hit a global ratelimit). The `LocalRatelimiter` takes a primitive approach and locally limits requests to 50 per seconds. However, as it can be "misaligned" with the actual bucket a 50req/1s can still cause up to 25 global ratelimit hits per second.

If you want to be 100% sure to not hit any global ratelimit, you would need to limit it to 25req/1s.


While I think about it...
A better solution to a local 25req/1s ratelimit is probably a finer ratelimit like 5req/110ms or even 1req/21ms. Unfortunately the `LocalRatelimiter` class does only support second-percision at the moment.

Can you please try the following ratelimiter:
```java
public class CustomLocalRatelimiter implements Ratelimiter {

    private volatile long nextResetNanos;
    private volatile int remainingQuota;

    private final int amount;
    private final int nanos;

    public CustomLocalRatelimiter(int amount, int nanos) {
        this.amount = amount;
        this.nanos = nanos;
    }

    @Override
    public synchronized void requestQuota() throws InterruptedException {
        if (remainingQuota <= 0) {
            // Wait until a new quota becomes available
            long sleepTime;
            while ((sleepTime = calculateSleepTime()) > 0) { // Sleep is unreliable, so we have to loop
                Thread.sleep(sleepTime / 1_000_000, (int) (sleepTime % 1_000_000));
            }
        }

        // Reset the limit when the last reset timestamp is past
        if (System.nanoTime() > nextResetNanos) {
            remainingQuota = amount;
            nextResetNanos = System.nanoTime() + nanos;
        }

        remainingQuota--;
    }

    private long calculateSleepTime() {
        return (nextResetNanos - System.nanoTime());
    }
}
```
with
```java
.setGlobalRatelimiter(new CustomLocalRatelimiter(1, 21_000_000)) // 1req/21ms
```
or
```java
.setGlobalRatelimiter(new CustomLocalRatelimiter(5, 110_000_000)) // 5req/110ms
```

If I'm not mistaken, this should not (or very rarely due variance in network latency) hit any global ratelimits but still allow for a throughput close to 50req/1s.

**Comment by AyuAi** [comment]
I will give this a shot. Thank you for the insight on this issue!

**Comment by coaxial1** [comment]
FYI I'm using the approach of letting through one request every 22ms with good success in Yunite. Works much better than the "bursty" approach in the current default local ratelimiter.

**Comment by Bastian** [comment]
Good to know, that it works in practice.
