### ISSUE TITLE
ServerUpdater#removeRolesFromUser removing all roles

### ISSUE THREAD

**Issue by ThatBlockyPenguin** [Javacord/Javacord#660]
I have a method that searches through all the roles a user currently has, and removes the roles that begin with a certain phrase. If I use `rolesToRemove.forEach(r -> user.removeRole(r))`, it runs a-ok. However, I know that a better way of doing it is to use a ServerUpdater. However, if I run `new ServerUpdater(server).removeRolesFromUser(user, rolesToRemove).update()`, it sure does remove the correct roles... along with every other role the user has, too. Not so great.

I'm using the latest Javacord (v3.1.1)
~Thanks!

**Comment by Vampire** [comment]
@Bastian this is rather critical and hits multiple users.
Pepich also wanted to open an issue about it and another user also just complained.
For that other user it is `canKickUsersFromServer()` that is misbehaving.
For Pepich it is `User#getRoles(Server)`.
The latter is the real problem, as the others use that method and thus behave wrongly.
The problem is easily reproducible and the cause is, that after your changes for intents, the `GuildMemberUpdateHandler` simply does not propagate the changes in roles to the `RoleImp`l` objects anymore.
The result of this is, that the roles do not know their users properly anymore but only the state when the bot was last restarted.

While thinking about it, this here could of course also be due to missing intents.

**Comment by Bastian** [comment]
> The problem is easily reproducible and the cause is, that after your changes for intents, the `GuildMemberUpdateHandler` simply does not propagate the changes in roles to the `RoleImp`l` objects anymore.
> The result of this is, that the roles do not know their users properly anymore but only the state when the bot was last restarted.

That's not fully true.
The `MemberImpl` object has a `roleIds` field that gets updated with the event. This is also what should be used for the `User#canXyz()` method.

The idea was to have the Member object as the SSOT and the `Role#getMembers()` method being a simple filter for `Server#getMembers()` with `User#hasRole(...)` but it seems like I forgot to update it.

**Comment by Bastian** [comment]
Regarding intents: Without the `GUILD_MEMBERS` intent, the `Role#getMembers()` method will obviously stop working.
However, the `User#getRoles(Server)` method will still return the correct roles if the user was retrieved from an event on the same server (e.g. from `MessageCreateEvent#getUser()`).

**Comment by Bastian** [comment]
The `ServerImpl#getRoles(User)` method is also wrong which is the reason why `MessageAuthor#canKickUsersFromServer()` is not working correctly. It should first check if the User object contains a member object and if this member belongs to the server. If yes, it should use this member object to retrieve the roles.

**Comment by Vampire** [comment]
Hm, ok.
I tested with all intents enabled and compared `Role#getUsers()` vs. `User#getRoles(Server)`.
The former always showed the roles at the time the bot was restarted.
The latter properly updated with adding and removing roles to users.
