### ISSUE TITLE
NPE when listener was running too long

### ISSUE THREAD

**Issue by KILLEliteMaste** [Javacord/Javacord#697]
```
[ERROR] 2021-01-11 00:04:03 [Javacord - Central Scheduler - 1] EventDispatcherBase - Interrupted a a listener thread for SERVERNAME, because it was running over 120 seconds! This was most likely caused by a deadlock or very heavy computation/blocking operations in the listener thread. Make sure to not block listener threads!
[ERROR] 2021-01-11 00:04:03 [Javacord - Central ExecutorService - 991] EventDispatcherBase - Unhandled exception in a listener thread for SERVERNAME
java.lang.NullPointerException: null
	at org.javacord.core.util.event.EventDispatcherBase.lambda$checkRunningListenersAndStartIfPossible$17(EventDispatcherBase.java:265) ~[javacord-core-3.1.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```
Note: The application was absolutely broken and I couldn't find the cause for it so far meaning I can't reproduce this

**Comment by Joshix-1** [comment]
The line: https://github.com/Javacord/Javacord/blob/3ea5c635d5aa78c1f800f700e15bbc354a28e7ea/javacord-core/src/main/java/org/javacord/core/util/event/EventDispatcherBase.java#L265

IntelliJ tells me that `taskQueue.poll()` returns null if `taskQueue` is empty.
But I don't see how that makes sense. [Before that](https://github.com/Javacord/Javacord/blob/3ea5c635d5aa78c1f800f700e15bbc354a28e7ea/javacord-core/src/main/java/org/javacord/core/util/event/EventDispatcherBase.java#L243) it checks if it is empty.

**Comment by Vampire** [comment]
Hm it is actually easily reproducible. :-/
```java
api.addMessageCreateListener(event -> {
    try {
        Thread.sleep(130_000);
    } catch (InterruptedException e) {
        e.printStackTrace();
    }
});
```
and then sending two messages the bot can see.
As soon as the listener for the first message times out, the NPE happens. :-(

**Comment by Vampire** [comment]
Btw., don't do this at home!
`Thread.sleep` is always never what you want and if there is an `InterruptedException` you must not ignore it but at least set the interrupted status of the thread again if you don't control the thread and know what you are doing.

**Comment by Vampire** [comment]
The problem is, like this:
- message X is sent
- listener L is queued for X
- message Y is sent
- listener L is queued for Y
- listener L blocks until it is interrupted from the central scheduler
- after the central scheduler interrupted L, it calls `checkRunningListenersAndStartIfPossible`
- central scheduler looks at the queue, sees there is a listener to call and submits a task A for that to the central executor (task A is the one that will call `pull()` on the queue)
- listener L handles the interrupted exception and resumes operation by finishing and returning which causes the central executor to also call `checkRunningListenersAndStartIfPossible`
- central executor still sees that the queue is not empty as A was not yet executed so it submits a task B for that to the central executor
- now task A and task B both will call `poll()` on the queue and the one coming second will have a `NullPointerException` for the `run` call

**Comment by Vampire** [comment]
Not only the `NullPointerException` is the problem actually.
It also means that the event processing order is not guaranteed anymore as mutliple events will be handled at the same time if the queue actually had more elements to process, so I think it should be at least medium priority.

**Comment by Vampire** [comment]
The main problem is, that the cancelling does remove the queue selector from `runningListeners` instead of leaving that to the scheduled task.
Probably because of the fear that the task is maybe not started yet and `cancel` will care for it to never start or similar.
But this is wrong and also the other fallback calls are unnecessary I think, as the task is definitely running when that code is executed.
I'll prepare a fix later.
