### ISSUE TITLE
[Text chat] DM issue with 3.1.3-SNAPSHOT

### ISSUE THREAD

**Issue by RedsTom** [Javacord/Javacord#707]
When an user tries to DM the bot, if the bot, on this running session, did not DM this user, the `MessageCreateEvent` won't be called

![image](https://user-images.githubusercontent.com/44524788/106768831-a0655b00-663c-11eb-8743-f1011e84ca64.png)

Javacord version : `3.1.3-SNAPSHOT`

**Comment by Vampire** [comment]
This broke with the switch to Gateway version v8, as for DMs no CHANNEL_CREATE messages are sent anymore before the MESSAGE_CREATE event which seems to have been an intentional change.

As workaround the old snapshot version `org.javacord:javacord:3.1.3-20201228.161159-6` can be used.

More info at https://github.com/discord/discord-api-docs/issues/2248.
The gist is that they intentionally do not send the channel creates anymore and we need to compensate this on Javacord side.
