### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by miny1997** [Javacord/Javacord#709]
Hello, when I want to send a message with ó, it sends Ã³. Apparently it is a encoding issues according to http://www.i18nqa.com/debug/utf8-debug.html . I use Windows 10 for deployment and testing.

**Comment by Joshix-1** [comment]
The issue is not a problem of Javacord. You are using a wrong encoding. You should use UTF-8!

**Comment by miny1997** [comment]
My files are stored in UTF-8. What else could be the problem?

**Comment by Vampire** [comment]
It is absolutely unimportant in which encoding the file is stored, as long as it can encode that character. The point is, that you have to use the same encoding for reading and writing a file.

That means, if you have that character on some file and you saved that file with `UTF-8`, then you also have to read that file using `UTF-8` and not the default encoding which may or may not work.

And if you have that character directly in your source code as hard-coded string and saved it in `UTF-8`, you also have to make sure that the one reading the file uses that encoding, in case of sources this is the compiler. So you have to tell all compilers you are using, like Gradle, Maven, your IDE, ... to use the correct encoding.

Alternatively to telling the compilers the correct encoding, you can also restrict yourself to plain ASCII in the source files, because those are identical in all relevant encodings. To then use special characters, you can either read them from a file, like a properties file, or you can use Unicode escapes in your Java sources. In the case of `ó` that would be `\u00F3`.

**Comment by miny1997** [comment]
Ok, id("com.github.sgtsilvio.gradle.utf8") version "0.1.0" as a plugin in my gradle file did it. I use hardcodes log messages, so I was suprised that it doesn't use Unicode.

**Comment by Vampire** [comment]
Don't confuse Unicode with an encoding that converts Unicode characters to bytes and the other way around. There are many different encodings out there, `UTF-8` is just one of them and one of these that can encode alli Unicode characters.

Gradle like most tools uses the default encoding of the system you are using unless you tell it differently. That default encoding can be any encoding, including `UTF-8`.

Be aware that if you also use your IDEs compiler, you might also have to tell that to use the right encoding.
