### ISSUE TITLE
RatelimitManager bug

### ISSUE THREAD

**Issue by dylhack** [Javacord/Javacord#752]
While iterating over 100k+ members of a server and removing each role, a stacktrace error occurs
```java
2021-05-21 11:54:45.875-0700 WARN org.javacord.core.util.ratelimit.RatelimitManager Encountered unexpected exception. {shard=0} 
 java.lang.NullPointerException
    at org.javacord.core.util.ratelimit.RatelimitManager.handleResponse(RatelimitManager.java:186)
    at org.javacord.core.util.ratelimit.RatelimitManager.lambda$queueRequest$2(RatelimitManager.java:138)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by dylhack** [comment]
The only REST related method I am calling is the `<User>.removeRole` method. I'm currently running a debugger in a dev environment to see what the request object looks like at `RatelimitManager.java:186`

**Comment by dylhack** [comment]
This isn't new to anyone perhaps, but the exception is thrown when this body is provided (seen below). Perhaps there's a better way of handling this in a unique exception rather than a NullPointerException?
```json
{
  "code": 0,
  "message": "You are being blocked from accessing our API temporarily due to exceeding our rate limits frequently. Please read our docs at https://discord.com/developers/docs/topics/rate-limits to prevent this moving forward."
}
```

I'm still investigating how I got to this though despite cooperating with Discord's rate limiting but I guess that would make this issue irrelevant.

**Comment by Joshix-1** [comment]
I think the issue is known, but I don't know if there is a fix yet.

Despite the bug in Javacord:
Why would you remove a role from all members of a server? You could just delete it. If that isn't an option you should use a ServerUpdate, because it has better performance, you can remove a role from multiple users with just one request.

**Comment by dylhack** [comment]
It's not all members I don't think my situation has anything to do with this bug, one way or another we got here.

**Comment by Joshix-1** [comment]
I know that your Situation has nothing to do with the bug, I just wanted to suggest, that you can use a ServerUpdater, to reduce requests.

**Comment by coaxial1** [comment]
I mean, to even come to the error you sent above, you have to violate ratelimits extremely frequently beforehand.

The question should rather be how that could have happened, rather than (while not completely irrelevant) why Javacord doesn't handle the temporary ban. Once Discord lifts your temporary ban, you should watch what your bot is exactly doing to violate ratelimits. It's especially relevant to look which ratelimits are being violated (a guild-scoped one, or maybe the global ratelimit?).

Does your bot operate on that server only or is it running on multiple servers? Are you running one shard or multiple shards?

**Comment by dylhack** [comment]
There are multiple bots running on server, sorry there was added context on the Discord. Perhaps another bot is causing issues and it's not this situation's problem (bulk managing member roles).
