### ISSUE TITLE
MessageComponentInteraction#createFollowupMessageBuilder#send fails on empty messages

### ISSUE THREAD

**Issue by elainecao93** [Javacord/Javacord#827]
**Expected behavior:**

`messageComponentCreateEvent.getMessageComponentInteraction().respondLater();` followed by `messageComponentCreateEvent.getMessageComponentInteraction().createFollowupMessageBuilder().send();`

results in the first line of code producing a "<bot name> is thinking..." message, and the second line of code "clearing" that message.

**Actual behavior:**

The second line of code doesn't seem to do anything, and no POST request is sent for it. The "<bot name> is thinking..." message hangs indefinitely.

The expected behavior would match up with how the ImmediateResponder works (with 'messageComponentCreateEvent.getMessageComponentInteraction().createImmediateResponder().respond();' ), where this causes Discord to acknowledge that the interaction is responded to, but without displaying a new message.

**Comment by coaxial1** [comment]
It doesn't make sense to send a follow up message right after using ``respondLater()``. You would need to update that message using the returned ``InteractionOriginalResponseUpdater`` to make the "thinking" message go away.

But, it seems like you want to just acknowledge the press of a button without responding. To do that, just use ``MessageComponentInteractionBase#acknowledge()``.

Lastly, the second line is of course doing something, but probably just fails due to the message being empty. Please log excpetion by attaching ``.exceptionally(ExceptionLogger.get());`` to both of your calls.

**Comment by elainecao93** [comment]
My code looks like this:

```messageComponentCreateEvent.getMessageComponentInteraction().respondLater();
// some stuff that takes about 5-10 seconds to process
// edit the original message using that result
messageComponentCreateEvent.getMessageComponentInteraction().createFollowupMessageBuilder().send(); ```

So my use case is that I want to make the "thinking" message appear, and then disappear after I finish processing the command, which means that #acknowledge doesn't really work. I've found a workaround (by editing the original message to say "thinking..." while its working), but that seems ugly. Its not that I'm sending the follow-up right afterwards, I just only posted the relevant parts.

> Lastly, the second line is of course doing something, but probably just fails due to the message being empty. Please log exceptions by attaching .exceptionally(ExceptionLogger.get()); to both of your calls.

No, there's no API call associated with the followUpMessageBuilder.send() call in the logger, and no exceptions are thrown.

**Comment by coaxial1** [comment]
Okay, but this is not how it works.

If you use ``respondLater()``, which internally sending a response type ``5``to the interaction, you have to use the returned ``InteractionOriginalResponseUpdater`` to edit or delete the "loading state" message within a timeframe of 15 minutes for the "thinking..." message to go away. Here's the relevant Discord doc for your reference: [Discord Docs](https://discord.com/developers/docs/interactions/slash-commands#interaction-response-object).

A follow up messages is **not** doing what you want in this case. A follow up message can be used to send another, entirely new message with additional information later, for example after a minute or whatever. It does not affect the initial reply.

To get rid of the "thinking..." message without editing it to something else, you can also use the delete endpoint for your interaction, which could be called in your case by
```java
messageComponentCreateEvent.getMessageComponentInteraction().respondLater()
    .thenAcceptAsync(updater -> {
    
        // Do your 10 second work
        
        updater.delete().exceptionally(ExceptionLogger.get());
    }).exceptionally(ExceptionLogger.get());
 ```

> API call associated with the followUpMessageBuilder.send() call in the logger, and no exceptions are thrown.

The exceptions are not visible from your code. Javacord is working with CompletableFutures, and Exception will just fail silently if you do not actively log or handle them otherwise using a ``.exceptionally()`` clause like in my example above.
There is probably no API call because you're trying to send an empty message, which is illegal and catched by Javacord. It would fail on Discords side anyways.
