### ISSUE TITLE
`BotInviteBuilder` shortcomings

### ISSUE THREAD

**Issue by Vampire** [Javacord/Javacord#908]
The `BotInviteBuilder` should allow to select for which scopes an invite link should be generated and whether a link for adding the bot or for just adding a scope should be generated.

**Comment by Saladoc** [comment]
Should this allow for *all* scopes or just `bot` and `application.commands`, in a way that allows future inclusion of other relevant scopes?

**Comment by ShindouMihou** [comment]
I had a little design concept for this [VelenBotInviteBuilder](https://github.com/ShindouMihou/Velen/blob/c97d4492ceb710f1164a59a1bc07102e42991fb1/src/main/java/pw/mihou/velen/utils/VelenBotInviteBuilder.java) that I kind of forgot about, though according to Vampire:

> For the PR you should probably remove the check for needed redirect url, as Javacord philosophy is to not duplicate checks done on the server.

I think it's a good idea to just include all the scopes since the target of Javacord is bot developers who tend to add a lot of random scopes and redirects. If we are adding invite scopes for `application.commands` and `bot` then why not just add the others as well for completeness?
